DROP DATABASE omnicanal;
CREATE DATABASE omnicanal;
USE omnicanal;

CREATE TABLE users (
id INT PRIMARY KEY AUTO_INCREMENT,
username VARCHAR(255) NOT NULL,
email VARCHAR(255) NO NULL,
password VARCHAR(255) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SHOW TABLES;

SELECT * FROM users;